### ISSUE TITLE
Allow for multiple sources?

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#125]
The original expectation for the `source` field was that it would typically specify the contest that the problem was created for. Naturally, some problems were not created for contests, but rather courses, or practice series, and that's also fine.

Lately (well, *mostly* lately) it has been that case that a given problem is created for multiple contest. In the past this was mostly due to new (or weak) contests using the problem set from another contest. That meant that the problem *set* was usually used as a whole, *and* there was a reasonable choice for source, since one of the contests had the problems, and shared it with another. Even in the past though there were a few cases were problem sets were created more jointly.

In any case, in the last several years, mostly in North America, problems have been developed jointly in a "Problem Pool" and then used in different configurations in several contests that run more or less at the same time.

The solution so far has been to set `source` to something like `2022 ICPC North America Regional Programming Contests (February 25, 2023)` ([you can see that on Kattis](https://open.kattis.com/problem-sources/2022%20ICPC%20North%20America%20Regional%20Programming%20Contests%20%28February%2025%2C%202023%29)).

To solve this we could:

1. Allow multiple sources, probably making it a "String or sequence of strings".
2. Ignore it, it's fine.
3. Rethink source?

Thoughts?

**Comment by thorehusfeldt** [comment]
While you think about these things, also consider adding a `version` to `problem` (_not_ referring to problem format.)

**Comment by Tagl** [comment]
When you say "rethink source", what do you mean?
What options are there other than no source, one source or multiple sources?

- No source sounds awful to me.
- One source works almost all the time, since in some (many?) of these cases there is some sort of umbrella source.
- Multiple sources sounds like a nice QoL change that does not get used very often, but I'm not seeing the implementation complexity change much so I think it's fine to support that.
