### ISSUE TITLE
Introduce version field in problem.yaml

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#18]
Introduce something like `problem_format_version` in `problem.yaml`.

This would be a required going forward, but tools could (and likely will) treat missing `problem_format_version` as a "compatibility mode".

(See also discussions in #15)

**Comment by jsannemo** [comment]
I like `problem_format_version`. `problem_spec_version` works too, but I think either is better than `format_version` or `spec_version` which is IMO too brief.

**Comment by niemela** [comment]
Regarding the value and semantics I suggest:

* A version string on the format `<yyyy>-<mm>` (like what we have in the [Contest API](https://github.com/icpc/ccs-specs).
* The version must be changed whenever there is a non-backwards-compatible change
* The version should not be changed for "bugfixes", i.e. when the intended meaning does not change, only the explanation or examples.
* The version does not have to be changed for added features, but could/should be for significant amounts of added features.

I.e. pretty weak guarantees. Only "if you recognize the version then all the things you know will mean what they think you mean, but there could be things you don't know". So, you can't just look at the version and know if you will be able to use the package, but you *can* look and version to know if you will be able to tell whether you can use the package.

I think only the last item is controversial? Thoughts?

**Comment by niemela** [comment]
Yeah, that's a very good point. It was kinda what I was getting at with the "significant amounts of added features" but that might be too vague/weak...

In fact we should bake the "subset" thing into this as well. Then the version string would be on the form `<yyyy>-<mm>[/<subset>]`. So e.g. `2022-09/icpc` would mean the icpc subset of the `2022-09` version of the format.

**Comment by jsannemo** [comment]
I guess. The main use case I can imagine for that is to force problemtools to explicitly disregard everything not in the `icpc` subset (or even complain about the presence of such aspects in the problem), to ensure that problems used at the WF only use features all judges support. (I considered a lot of other use cases, but they seemed contrived, confusing or unlikely to be useful in practive -- but maybe you have thought of some).

I'm not 100% convinced that use case alone is worth it to be included in the versioning string rather than having a separate tool or just a verifyproblem flag for ICPC WF judges when testing their problems.

I also don't really care since I would never use the `/icpc` subset, so feel free to ignore my opinion.

**Comment by jsannemo** [comment]
I'm fine with a judge accidentally including more features than bargained for; it's unlikely to be a problem in practice, unlike changing the meaning or removing functionality old problems may be using. However, I'd prefer bumping the version when new functionality is added.

The older version of the spec at problemarchive.com used to display exactly what was implemented and what was not (in Kattis). This was neat, since I mostly didn't accidentally use unsupported functionality, except that "implemented" sometimes meant implemented in /problemtools/ rather than /kattis/ (this is not a match even today, since kattis uses an old problemtools version).

Of course, you might say: let a judge just take a commit of this repo and say "this is the features we support". But then, why not just bump the version and point to that as supported?

**Comment by eldering** [comment]
I think that the the version number should be bumped both when backward *and* forward incompatible changes are made to the spec. The reason is that declaring a version number in the problem package should also be seen as a requirement from the judge that anything in that spec version will be supported by the tool/CCS loading that problem package. For example, say that a new keyword `foobar` is added for the `validator` key in `problem.yaml`. This is backward compatible. But if the tool doesn't implement this `foobar` validator while the judge assumes it does, then the system may (silently) not operate as expected.

Besides that, I think it's fine that a judge specifies extra features in the problem package that are not part of the specified spec version, or that the tool supports extra features. Ideally, I think the tool should warn about any extra features it reads but doesn't support.

**Comment by niemela** [comment]
> whereas with version numbers I can just implement everything,

Are you planning to implement everything? I thought you said earlier that you would only implement the ICPC subset. The more tools that are actually aiming for a subset, the more useful/needed specifying such a subset is. If everybody is implementing everything, than it's clearly unnecessary.

**Comment by niemela** [comment]
Sounds like the consensus is that we want a bit stricter semantics. I.e. the version should change for any (non-trivial) change. I also agree with that.

It's not entirely clear to me how "non-trivial" should be defined. It should include improved wording and examples and bugfixes, and maybe nothing else. Thoughts?

**Comment by eldering** [comment]
Done in #47
