### ISSUE TITLE
Limit validation_passes

### ISSUE THREAD

**Issue by mzuenni** [Kattis/problem-package-format#205]
@meisterT mentioned that it might be a good idea to add a limit on the number of passes. Maybe we should ad something like this to the Limit entry in the problem.yaml:

| Key | Comments | Default | Typical system default |
| - | - | - | - |
| validation_passes | optional | system default | 2 |

**Comment by RagnarGrootKoerkamp** [comment]
Is this not something a validator can handle itself? Or more as a safety guard?

**Comment by eldering** [comment]
> Is this not something a validator can handle itself? Or more as a safety guard?

The intent was as a safety guard for faulty validators indeed, see https://github.com/DOMjudge/domjudge/issues/2307#issuecomment-2156671504

**Comment by meisterT** [comment]
Additionally, it serves as an upper bound for how long a submission might occupy a judgehost. Right now you can take the product of time limit and number of test cases. With multi pass problems you need to factor in the number of passes as well.

**Comment by niemela** [comment]
This sounds (IMO) like a good idea. Some questions and thoughts below...

What would the result of surpassing the limit be? I would argue that the purpose of this is internal validation, so the result should be "Judge Error". If you want a problem with (in some sense) variable number of passes, but where surpassing some maximum limit fails the submission, than the correct way to implement that would be in the validator, *not* by setting this limit.

I'm not sure if the use "system default" is proper in this case. The original reason for this was to make problem packages more "portable" or "time independent". I.e. 128MiB might have been a "reasonable" memory limit some decades ago, and 8GiB might be a "reasonable" memory limit in the future. The "system default" is intended for cases where you don't really care about e.g. the memory limit, because it's not the point of the problem, so the system can just pick "something reasonable". I would argue that a limit on the number of passes is not such a limit. It is always the "point of the problem". I suggest we change the default to some value. 2 would not be an unreasonable value, because 2 is probably the most common number of "multi" passes.

How do we want to handle variable or "unbounded" number of passes? Do we want to handle that? This suggestion kinda disallows "infinite" passes (which, when you write it out, sounds like a really good thing). What should an author if they have a problem that truly does have a variable number of passes? Just pick some very high number (and then also implement counting in the validator, to fail the submission at that limit, and the also add a submission that does whatever is needed to trigger "infinite" passes to make sure that that fails and does not JE)?

**Comment by mzuenni** [comment]
> How do we want to handle variable or "unbounded" number of passes? Do we want to handle that? This suggestion kinda disallows "infinite" passes (which, when you write it out, sounds like a really good thing). What should an author if they have a problem that truly does have a variable number of passes? Just pick some very high number (and then also implement counting in the validator, to fail the submission at that limit, and the also add a submission that does whatever is needed to trigger "infinite" passes to make sure that that fails and does not JE)?

Yes, WA should always come from the validator, too many passes should be JE (same as for the other validation limits).
