### ISSUE TITLE
Problem statements needs to be better specified

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#31]
What exact LaTeX environment can/must be assumed.

**Comment by niemela** [comment]
@austrin Could you help with this one?

**Comment by jsannemo** [comment]
I think we should define a "HTML-friendly" subset, that implmentations must promise to be able to convert to HTML.

It should still be allowed to go outside of this subset. A CCS for example compile that LaTeX using a provided problem class name, and instead host a PDF upon installation.

**Comment by evouga** [comment]
This seems *incredibly* daunting... a starting point might be the subset supported by mathjax, which is [quite extensive](https://onemathematicalcat.org//MathJaxDocumentation/TeXSyntax.htm).

In fact maybe the reasonable path here is to pick the same subset as a common TeX Javascript display engine like mathjax (which strongly encourages, but doesn't formally require, a CCS to use that engine).

**Comment by niemela** [comment]
This is what Polygon supports: https://polygon.codeforces.com/docs/statements-tex-manual

**Comment by niemela** [comment]
In addition to what Polygon supports we should probably support:
```
\begin{figure}
\begin{verbatim}
\begin{quote}
\begin{array}
\begin{minipage}
\begin{wrapfigure}
\section
\textwidth
\ldots
\noindent
```

**Comment by RagnarGrootKoerkamp** [comment]
This is the class file we use for BAPC
https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/latex/bapc.cls
Apart from that, we only have a light wrapper around problems
https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/latex/problem.tex

Note that we also inject `\problemlabel` and `\problemauthor` that are mostly used in solution slides rather than statements.
