### ISSUE TITLE
How are `.files` handled

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#332]
Comments from @gkreitz (translated from Swedish):
> `.files` should be copied into the working directory (of the submission and output validators...). When should that happen? Specifically, before or after static validation runs?

**Comment by Tagl** [comment]
The `.files` functionality is irrelevant for static validation since either those files you need for the test case would be included in the submission by the submitter, or with `include`, or provided with the static validator.
The static validation test case is defined in the testdata.yaml so no .files can be provided either.
Therefore, there is no before or after to consider.

We should probably clarify this though.

**Comment by niemela** [comment]
> The `.files` functionality is irrelevant for static validation

Right, `.files` is part of the "input", i.e. for the "dynamic" validation.

**Comment by Tagl** [comment]
Can this be closed then or is there something else unanswered here?
