### ISSUE TITLE
Licenses: custom licenses

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problem-package-format#39]
The problem format forces a set of allowable licenses. Nice in practice, but does it belong there?

**Comment by evouga** [comment]
Main issue here is that users will enter a diversity of synonyms and typos of common licenses instead of a canonical license name. Moreover many licenses have requirements about how they're cited (for example Creative Commons requires a hyperlink to the license text) and compliance with such clauses requires the contest system to know about the license.
