### ISSUE TITLE
Output-only problems

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problem-package-format#46]

**Comment by evouga** [comment]
To be clear, this issue refers to problems where contestants submit the output itself (instead of a program that computes the output).

**Comment by niemela** [comment]
@jsannemo Any ideas on how to do this best?

I don't think I would be against it, but if we don't know how to do it yet, maybe we should cut it for now?

**Comment by jsannemo** [comment]
The obvious way is IMO to have a problem.yaml flag for this that signals "teams should create submissions by submitting the .ans files matching a subset of the .in files". Some details remain on what to do for a submission that doesn't include *all* .ans files.

**Comment by niemela** [comment]
> The obvious way is IMO to have a problem.yaml flag for this that signals "teams should create submissions by submitting the .ans files matching a subset of the .in files". 

This property is orthogonal to `pass-fail` vs `scoring` so it needs to be something else than `type` (or we need 4 values for type).

It's somewhat related to `languages` in the sense that it is a bit like allowing *no* languages.

> Some details remain on what to do for a submission that doesn't include _all_ .ans files.

Uploading a set of files should have the same effect as if a program would have produced those files. Submission that are missing some files should be treated as if that file was empty, or alternatively always fail (for that case).

**Comment by RagnarGrootKoerkamp** [comment]
Probably a new `output-only: true` flag is needed then?

So for pass-fail problems, the only way to solve the problem is to upload the set of all `.ans` files at ones and they must all be correct.

For scoring problems, you can't first submit `1.ans`, then `2.ans`, then `3.ans`, because your score would be `max(score 1.ans, score 2.ans, score 3.ans)`, instead of `sum(score 1.ans, score 2.ans, score 3.ans)`, so you have to incrementally submit more and more files. (Well, unless the judge does some special handling but that sounds like a lot of work.)

**Comment by Tagl** [comment]
I'd say it's kind of like adding a single language that is similar to echo and restricting to that language. Isn't that how you'd accomplish this now, that is provide a driver in a specific language that simply outputs the contents of the correct file?

If I wanted to do something like this I'd just use include but it would be nicer if the language of the submission was Text or Files or something instead of C++/Python. I'm not sure this is really a new type of problem but rather just some sort of language option.

**Comment by Tagl** [comment]
Alright, yes I do agree now that this is a different type.
This kind of falls under validation, but with drastic changes and is not really compatible with the other options there.

And I must say, I do love this idea. Allows for Capture the Flag, but is more powerful.

**Comment by niemela** [comment]
> This kind of falls under validation, but with drastic changes and is not really compatible with the other options there.

This is of course subjective rather than objective truth, but I feel that `output-only` (and also `multipass`) is more of a `type` thing than a `validation` thing. Also, `interactive` is a bit border line...

Speaking of `validation`, do we actually *need* to specify `scoring` there?

**Comment by RagnarGrootKoerkamp** [comment]
pass-fail would work fine even for output-only. Either with a single
testcase or multiple

**Comment by Tagl** [comment]
> Speaking of `validation`, do we actually _need_ to specify `scoring` there?

I think I asked this question in Lund and someone claimed this was to verify the intent in the validator I think.
That is, if the validator outputs score.txt and scoring is not present it is an error and vice versa.
I don't think it is necessary, score.txt is optional and should be used to override the defaults.
If this were an error it would very likely pop up elsewhere in the process.

Personally, I'd even remove pass-fail from type and then scoring would go from type as well, but we have default values now based on pass-fail/scoring so we'd have to revert that.
If we did that then type would actually signify the *type* of the problem, instead of binary vs non-binary grading scheme.

**Comment by niemela** [comment]
> Personally, I'd even remove pass-fail from type and then scoring would go from type as well, 

Really?

> but we have default values now based on pass-fail/scoring so we'd have to revert that.

That would be easy enough if we want to go that route.

> If we did that though, then type would actually signify the _type_ of the problem, instead of binary vs non-binary grading scheme.

What *is* the *type* then, in your opinion? To me `pass-fail` vs `scoring` is definitely part of the type, and I think `input-ouput` vs `output-only`, and `single-pass` vs `multi-pass` would also make sense. (And, as mentioned earlier, I don't really know what to do with `interactive`).

**Comment by Tagl** [comment]
I think standard I/O, output only, multi pass are all way more suitable as types than pass-fail / scoring.
Pass-fail is just one very specific configuration of scoring in my mind.
You can make a scoring problem and set up the testdata.yaml files so that it is a pass-fail problem.
I guess the hiccup there *might be* verdict aggregation.

Technically, multi-pass runs the program n>=1 times and single-pass is just multi-pass with n=1, not sure that it needs another type either since the output validator will signify whether there is another run.

However, if you have all of these as types, you can still have multi-pass and interactive so I'm not sure interactive really falls under type.

**Comment by ghamerly** [comment]
I doubt this is a helpful comment to this conversation, but I wanted to point out that even though Kattis does not currently support the "Text" language, one can use PHP for "output-only" -- by leaving out `<?php ... ?>` blocks. Many teams used this in the ICPC challenge several years ago. (Yes, I know this is only slightly better than a program that just prints the answer, and yes I know that it doesn't generalize to multiple tests.)
