### ISSUE TITLE
Specify working directory for validators, graders, and generators

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#5]
Especially important when the program is a directory

**Comment by eldering** [comment]
Also relevant: what happens after compilation: e.g. do only Java class files get copied to the build directory, or also other (e.g. data) files?

**Comment by RagnarGrootKoerkamp** [comment]
for BAPCtools: everything is run in some directory in `/tmp/bapctools...`.
So really it can be anywhere:
- not the directory of the testcase being validated/generated
- not the directory of the program itself

Basically:
1. the file being run (or all files in the directory) are copied to some dir in tmpfs
2. `build` is executed there if present; otherwise build the cpp/java/... according to the language.
3. The `run` file is now the executable for this program.

**Comment by RagnarGrootKoerkamp** [comment]
After some discussion: it seems achievable and nice to always (for both solutions and validators) set the CWD the directory of the program (/the executable) as the CWD.

*new idea*: input+output validators:
`/data_validators/validator.py`
that validates both input and output at the same time
`validator.py <path/to/testcase.in> <path/to/testcase.ans> <validator_flags> < testcase.in`

- postpone for now; there are issues when .in is invalid and it does not make sense to
  generate a .ans.

* GOAL: Every program that's run has itself as CWD

**Comment by niemela** [comment]
@eldering Will be looking into how this could be  done (in DOMjudge) and report back.

**Comment by niemela** [comment]
> @eldering Will be looking into how this could be done (in DOMjudge) and report back.

@eldering Bump?

**Comment by niemela** [comment]
@RagnarGrootKoerkamp @eldering @pehrsoderman What do we want to do with this issue? Can we close it maybe?

**Comment by eldering** [comment]
Sorry, I've been too busy/distracted with moving house and other things. I think this should still be addressed, but we could keep it out of the to-be-released version of the spec.

**Comment by Tagl** [comment]
Want to be able to specify fixed file path "Your program will have access to countries.txt and cities.txt" for example.
Some files are code files and other are data files. The idea now is:
- Rename included files to included code again because code is included in the compilation process. This is used to pass in code files which we will not specify whether are accessible in the working directory, or at all to the program. Do we need include/all?
- The binary that is run can be reached using argv[0] but we don't say anything about its relative path to the working directory.
- We use the .files as data files to provide. It is maybe not the greatest when you have the same data file for each test case but it allows us to separate source files from data files, which potentially get different treatments within compilation and running step.
- How to handle splitting submission files as sources files/data files?

**Comment by niemela** [comment]
> It seems that instead of saying `the working directory of a program (submission/validator/interactor/...) is X`, we want to say `the working directory contains files X, Y, Z`.

Agreed. We might also want to say `the working directory does not contain files X, Y, Z`.

> `testcase.{in,ans}` (2) are passed on `stdin` and/or as paths, so do not need to be in CWD.

I would argue that for submissions this **must not** be in CWD. Definitely for `.ans`, probably also `.in`.

> I regularly run into cases where (a) would help, and so far not into (b), so if we do not want to do both (a) and (b) I would prefer (a).

Could you elaborate on what the cases for (a) that you run into could look like?

We have at least one problem on Kattis where the expected solution "requires" (or at least assumes) (a): https://open.kattis.com/problems/dictionary

I would argue that (b) (which I interpret as files provided in `.files`) is an absolute must.

So, I think we need to do (a) and (b).

**Comment by niemela** [comment]
I think we have agreement on this then.

@RagnarGrootKoerkamp Do you want to draft a PR, or would you prefer if I took a stab? My sense is that you would be better at this?

**Comment by Tagl** [comment]
So if I am understanding correctly, since we need (a) then we can still provide data files using `include`?

**Comment by eldering** [comment]
> So if I am understanding correctly, since we need (a) then we can still provide data files using `include`? The only reason we had for not doing that was the quine example Fredrik suggested in Delft, I think.

Wait, but @Tagl you're talking about what's available to (compiled) submissions, right? I think it's good to distinguish that from validators,graders,etc. as the latter are created by the jury, so can be considered safe, while contestant submissions cannot, so we should be a lot more careful there. And then the extra (CCS implementation specific) sandboxing requirements may make it more difficult to guarantee stuff.

**Comment by Tagl** [comment]
> I think it's good to distinguish that from validators,graders,etc. as the latter are created by the jury, so can be considered safe, while contestant submissions cannot, so we should be a lot more careful there.

I suppose so, I always considered them in the same way since privileged data was passed to the validators using arguments so there really wasn't need for them to be treated differently if you simply don't pass the privileged data to the submissions. So my idea was that all programs are treated equally, except that submissions can't use build/run.

**Comment by niemela** [comment]
> So if I am understanding correctly, since we need (a) then we can still provide data files using `include`?

I think that's a logical consequence, yes.

> The only reason we had for not doing that was the quine example Fredrik suggested in Delft, I think.

And that's not really a serious example.

---

> Wait, but @Tagl you're talking about what's available to (compiled) submissions, right? I think it's good to distinguish that from validators,graders,etc. as the latter are created by the jury, so can be considered safe, while contestant submissions cannot, so we should be a lot more careful there. And then the extra (CCS implementation specific) sandboxing requirements may make it more difficult to guarantee stuff.

I would really like to sandbox jury provided code as well.

IMO the difference is rather that file access *must* be very clear and simple for user submissions, where as for jury code simple is great, but clear an well defiend is good enough. I.e. i think it's a must that if a user submission needs to open a textfile it should be  `file.txt` directly in the CWD.

**Comment by eldering** [comment]
> I would really like to sandbox jury provided code as well.

Sure, but I think that's a different level of requirement than sandboxing the user submission, and since implementations (i.e. CCSes) might do this differently for submissions and jury code (if done at all), we should be careful not to force submissions and jury programs together here.
 
> IMO the difference is rather that file access _must_ be very clear and simple for user submissions, where as for jury code simple is great, but clear an well defiend is good enough. I.e. i think it's a must that if a user submission needs to open a textfile it should be `file.txt` directly in the CWD.

Agreed here.
