### ISSUE TITLE
Custom graders: are they needed?

### ISSUE THREAD

**Issue by evouga** [Kattis/problem-package-format#64]
Are the testdata features rich enough to make these an unnecessary complication?

**Comment by niemela** [comment]
First reaction: yes!

...but are they actually?

@simonlindholm @jsannemo @pehrsoderman @austrin @ghamerly ?

**Comment by jsannemo** [comment]
I lean towards... no? "Needed" is subjective as always, but I am happy to force people into things supported by the default grader. For PO we used it a lot in legacy problems before subtasks became a thing.

**Comment by simonlindholm** [comment]
For the Swedish olympiads, it looks like in the past few years we've only used them for clamp scores to at most 100 for data/ while allowing data/secret/ to exceed that, for heuristic problems. Might have been a safety measure, I don't know. See e.g. <https://github.com/Kodsport/swedish-olympiad-2023/tree/main/final/berguppdelning>, <https://github.com/Kodsport/swedish-olympiad-2023/tree/main/online/tomtplanering>, <https://github.com/Kodsport/swedish-olympiad-2022-public/tree/main/onlinekval/ljusshow2>.

(<https://github.com/Kodsport/swedish-coding-cup-finals-2022/tree/main/addingupthevotes> also uses a custom grader to implement scoring within grader.py instead of in the output validator, but there's no reason for that that I can tell)

We've used them in the past to implement weird school qualification round rules ("there are X test cases, if you solve Y of them you get Z points"), but I think we've recently moved towards modifying scoring/test groups/test cases of those problems as part of uploading them to Kattis.

I think we've also sometimes wanted to use them to work around missing support for output validator flags in Kattis, and for the use-case mentioned in #16, but it doesn't seem like we have actually done that in the past few years.

**Comment by jsannemo** [comment]
> For the Swedish olympiads, it looks like in the past few years we've only used them for clamp scores to at most 100 for data/ while allowing data/secret/ to exceed that, for heuristic problems. Might have been a safety measure, I don't know. See e.g. https://github.com/Kodsport/swedish-olympiad-2023/tree/main/final/berguppdelning, https://github.com/Kodsport/swedish-olympiad-2023/tree/main/online/tomtplanering, https://github.com/Kodsport/swedish-olympiad-2022-public/tree/main/onlinekval/ljusshow2.

The reason was that we wanted to let the contestant see their pre-clamped score. But this is the wrong way: we should have done that using teammessage.txt.

> (https://github.com/Kodsport/swedish-coding-cup-finals-2022/tree/main/addingupthevotes also uses a custom grader to implement scoring within grader.py instead of in the output validator, but there's no reason for that that I can tell)

No, not really. "It's easier to change python code than cpp". I think we might have had some thoughts around more complicated grading, but decided against it.

> We've used them in the past to implement weird school qualification round rules ("there are X test cases, if you solve Y of them you get Z points"), but I think we've recently moved towards modifying scoring/test groups/test cases of those problems as part of uploading them to Kattis.

Yeah, I have retroactively started changing this to be proper test group/test case scoring instead.

> I think we've also sometimes wanted to use them to work around missing support for output validator flags in Kattis, and for the use-case mentioned in #16, but it doesn't seem like we have actually done that in the past few years.

And it's a poor reason for keeping them anyway (and we have other workarounds).

**Comment by simonlindholm** [comment]
teammessage.txt doesn't work across multiple testcases, though

**Comment by jsannemo** [comment]
That's an implementation detail on the part of the CCS, not the spec though.

**Comment by simonlindholm** [comment]
Well, partly. But if you say have a problem with 100 test cases, scored from 0..100+ (clamped to 100) with min aggregation, you don't want to expose messages for each test case, but just a single message summarizing the unclamped minimum, and that's not possible with teammessage.txt. It also feels weird to me to even expose teammessage.txt for accepted test cases in contest settings where individual test cases aren't shown.

I do agree with the overall desire to simplify the format, and wouldn't cry too much to see graders removed.
