### ISSUE TITLE
Terminology for `short_name`

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#99]
Currently, the name of the problem directory is most often called `short_name`. This is confusing because many things have names (validators, test cases, submissions), so “the short name” is not very informative.

I think better suggestions are

1. `problem_id`. I prefer this, it can also appear in body text as ”the problem ID”. Short enough to be used in longer strings such as `<problem_id>/data/sample`. Also separates the concept “name” (like “Hello World!”, “Bonjour le Monde!”) from the concept ID (like `hello`).
2. `problem_short_name`. This would necessity “the problem’s short name `problem_short_name`”. Worse because `listgame2` is not a short form of the name “A Different List Game”.

**Comment by RagnarGrootKoerkamp** [comment]
`problem_id` SGTM

**Comment by Tagl** [comment]
I personally use problem ID and used that for many years before reading the spec and learning it was called short name.
I vote for `problem_id`.

**Comment by RagnarGrootKoerkamp** [comment]
We could similarly define terminology arounnd testcases:
- `testcase ID`: `secret/group/1`

**Comment by eldering** [comment]
`problem_id` sounds ok to me, but please be aware of the different things we already have at https://ccs-specs.icpc.io/draft/contest_api#problems:

- id
- label
- name

But indeed, `problem_id` corresponds with `id` there, so sounds fine.

**Comment by thorehusfeldt** [comment]
Thank you. That looks like a well-designed specification; we should aim for the same level of clarity and terminological stringency.

**Comment by jsannemo** [comment]
I don't like ID, mostly because it implies a uniqueness, which we have no way of enforcing (that's the UUID field is for). Personally I just call this the name, and what the spec calls the name the title. But I'm weird that way.

Short name is of course a misnomer, considering that it's not actually that short.

I don't have much to contribute for alternative ideas though.

**Comment by niemela** [comment]
> Currently, the name of the problem directory is most often called `short_name`. This is confusing because many things have names (validators, test cases, submissions), so “the short name” is not very informative.

I *really* don't see the issue. Of course many things have names, but if we're talking about *the* short name in the context of a problem package, it's the short name of the problem (or possibly the problem package, but I would argue that those are the same, and that does not seem to be the confusion you are referring to?)

I don't like ID because it's not an ID. The UUID is.

I don't think it's a misnomer, it is actually pretty short, and it is (typically) shorter than the "name", which is what makes it the "short name".

Regarding the other similar terms we use in the CCS specs, this is not an ID, it's not really an labal, it *is* a name. Specifically a slightly shorter (and uglier, and more URL friendly) name. I think `short_name` and `name` fits this pretty well, but I guess `name` and `display_name` could work instead?

Adding `problem_` in front of whatever we otherwise agree on would of course make it even more clear, but I don't think that's needed.

**Comment by jsannemo** [comment]
> I think short_name and name fits this pretty well, but I guess name and display_name could work instead?

I like that slightly better.

> I don't think it's a misnomer, it is actually pretty short, and it is (typically) shorter than the "name", which is what makes it the "short name".

"typically" depends strongly on your sample. I picked three random contests:
- https://pofinal22.kattis.com/contests/pofinal22/problems: all are the same
- https://open.kattis.com/problem-sources/Northwestern%20Europe%20Regional%20Contest%20%28NWERC%29%202017: 8/11 are the same
- https://open.kattis.com/contests/mcpc22open/problems: all are the same

**Comment by thorehusfeldt** [comment]
The `problem_id` is not displayed, as far as I know, so I'd be confused by the term `display_name`.

**Comment by jsannemo** [comment]
You flipped his suggestions around: `hello` is the `name`, and Hello World! Is the `display_name`.

I really do not like `problem_id`. From the point of a problem author I guess it's somewhat reasonable, but it would be incredibly confusing as a judge system implementer, where you typically have your own internal thing which is your `problem_id`.

I think the current de facto term `short_name` is much better than `problem_id`.

In fact, `short_name` *and* `display_name` might be a good set of terms, to avoid using the terribly overloaded `name`.

**Comment by jsannemo** [comment]
You flipped his suggestions around: `hello` is the `name`, and Hello World! Is the `display_name`.

I really do not like `problem_id`. From the point of a problem author I guess it's somewhat reasonable, but it would be incredibly confusing as a judge system implementer, where you typically have your own internal thing which is your `problem_id`.

I think the current de facto term `short_name` is much better than `problem_id`.

In fact, `short_name` *and* `display_name` might be a good set of terms, to avoid using the terribly overloaded `name`.

If you specifically dislike `short_name` because it doesn't include `problem_` as a prefix, I guess we could write it out. It's not actually used anywhere in files though right, only as a placeholder in the spec?

**Comment by nickygerritsen** [comment]
> I really do not like `problem_id`. From the point of a problem author I guess it's somewhat reasonable, but it would be incredibly confusing as a judge system implementer, where you typically have your own internal thing which is your `problem_id`.
> 

As a judge system implementer, I'm not sure if I agree, given that the [contest package format](https://ccs-specs.icpc.io/2023-06/contest_package#package-contents) also uses the ID of an endpoint (i.e. the problem ID) to store files in it's structure. Doesn't it kinda make sense to use the same terminology here? Moreover the [CCS spec](https://ccs-specs.icpc.io/draft/contest_api#problems) says for ID: "Identifier of the problem, at the WFs the directory name of the problem package.".

**Comment by jsannemo** [comment]
That sounds like an ICPC-specific term `icpc_problem_id`, in a situation where the shortname *is* indeed a unique identifier, since it's only used in a single contest. Things are not as simple for judging systems that live outside of both the ICPC world and the single-contest world.

For us, that the folder name *is not an identifier*. Just over a few years of Swedish olympiads we have reused the same shortname multiple times.

**Comment by nickygerritsen** [comment]
That is a fair point. I think even we have reused problem folder names many times between different contests.

**Comment by thorehusfeldt** [comment]
If the change

* `name` -> `title` 
* `\problemname` -> `\problemtitle`

is realistic, I’m _for_ it. (But I didn’t originally advocate that change.) 

_Title_ is better than _name_ because

1. it’s a more precise word (title of book, name of author.)
2. it’s more natural to have problem _titles_ in many languages
3. many things in the documentation and code  have “names” but (problem) _title_ is clear
4. it avoids the above confusion. The name of the problem can now be the `short_name` or even `problem_name` or even just `name`, and I could say “the name of the problem” in body text.
5. Johan thinks of it as _title_ anyway. ;-)

Note that `name`  is the _only_ required_ key in `problem.yaml`, so I’d normally be quite reluctant to change it.

I’d then propose `<short_name>` -> `<problem_name>` or even `<name>` in the documentation, but it’s much less of an issue now.

**Comment by thorehusfeldt** [comment]
If the change

* `name` -> `title` 
* `\problemname` -> `\problemtitle`

is realistic, I’m _for_ it. (But I didn’t originally advocate that change.) 

_Title_ is better than _name_ because

1. it’s a more precise word (title of book, name of author.)
2. it’s more natural to have problem _titles_ in many languages
3. many things in the documentation and code  have “names” but (problem) _title_ is clear
4. it avoids the above confusion. The name of the problem can now be the `short_name` or even `problem_name` or even just `name`, and I could say “the name of the problem” in body text.
5. Johan thinks of it as _title_ anyway. ;-)

Note that `name`  is the _only_ required_ key in `problem.yaml`, so I’d normally be quite reluctant to change it.

I’d then propose `<short_name>` -> `<problem_name>` or even `<name>` in the documentation, but it’s much less of an issue now.

**Comment by niemela** [comment]
> > I don't think it's a misnomer, it is actually pretty short, and it is (typically) shorter than the "name", which is what makes it the "short name".
> 
> "typically" depends strongly on your sample. I picked three random contests:

The short name tends to be the a few words from the full name (removing spaces).  So, in cases where the name is already short, the short name is not much shorter, in the special case when the name is already short and also a single word, the short name is the same (but lowercased). This is reasonable.

>     * https://pofinal22.kattis.com/contests/pofinal22/problems: all are the same

These are all a single word and other than "legobyggartavlingen" are already very short.
 
>     * https://open.kattis.com/problem-sources/Northwestern%20Europe%20Regional%20Contest%20%28NWERC%29%202017: 8/11 are the same

No, actually only 1 is the same, 7 is dropping a space, 3 are dropping some words (and spaces). 
 
>     * https://open.kattis.com/contests/mcpc22open/problems: all are the same

No, they are all dropping spaced. IMO, some of these are not good short names though...

**Comment by niemela** [comment]
> For us, that folder name _is not an identifier_. Just over a few years of Swedish olympiads we have reused the same shortname multiple times.

There is no requirement that the short name is globally unique.

**Comment by jsannemo** [comment]
> > For us, that folder name _is not an identifier_. Just over a few years of Swedish olympiads we have reused the same shortname multiple times.
> 
> There is no requirement that the short name is globally unique.

Yes, that is the point I was making. Personally I try to restrict the use of the term "ID" to things that *are* unique within the context they can appear in, which for us is not "a contest", but rather "a judging system" -- so I dislike calling the shortname "problem ID".

**Comment by jsannemo** [comment]
> > > I don't think it's a misnomer, it is actually pretty short, and it is (typically) shorter than the "name", which is what makes it the "short name".
> > 
> > 
> > "typically" depends strongly on your sample. I picked three random contests:
> 
> The short name tends to be the a few words from the full name (removing spaces). So, in cases where the name is already short, the short name is not much shorter, in the special case when the name is already short and also a single word, the short name is the same (but lowercased). This is reasonable.
> 
> > ```
> > * https://pofinal22.kattis.com/contests/pofinal22/problems: all are the same
> > ```
> 
> These are all a single word and other than "legobyggartavlingen" are already very short.
> 
> > ```
> > * https://open.kattis.com/problem-sources/Northwestern%20Europe%20Regional%20Contest%20%28NWERC%29%202017: 8/11 are the same
> > ```
> 
> No, actually only 1 is the same, 7 is dropping a space, 3 are dropping some words (and spaces).
> 
> > ```
> > * https://open.kattis.com/contests/mcpc22open/problems: all are the same
> > ```
> 
> No, they are all dropping spaced. IMO, some of these are not good short names though...

Clearly I didn't consider dropping spaces as "shortening the name", and I know you understood that from context. :)

Anyway, I don't really care what it is called except really disliking introducing the term "problem ID".

Fwiw "short name" *is* a very common name in computing for this particular type of identifier. So it's not extremely unusual.

I like @thorehusfeldt's suggestion in theory,  but suspect that there might be some non-negligible cost to moving from `\problemname` to `\problemtitle` unfortunately, so there might be some opposition to it?

Anyway, I'm going to throw in a compromise suggestion in calling this the `problem_short_name`: it's still only used as a problem spec placeholder, so I think it's fine if it's a bit long, and with the `problem_` there's not really much room for misunderstanding.

**Comment by thorehusfeldt** [comment]
Honest question: Is the problem ID that Open Kattis uses (which until recently was visible in the UI, but now is hidden away and only can be found in the problem URL) the `name_of_problem_package_directory` ? (My experience tells me yes, because I’ve been asked to change the `name_of_problem_package_directory` a few times.) But there may be a further level or reference I’m not privy to (such as mapping the `open_kattis_url_base` to `name_of_problem_package_directory` .)

**Comment by jsannemo** [comment]
Yes, but also no: it can be overridden upon installation, but the default is to use the package directory name. As you note, it's most often used for the `blah.` namespacing mechanism (since dot's are forbidden in the spec).

**Comment by niemela** [comment]
> Clearly I didn't consider dropping spaces as "shortening the name", and I know you understood that from context. :)

Yes, I understood, but I wanted to make clear why I don't agree with you, because I *do* consider dropping spaces as shortening. (Not by much of course).

> Anyway, I don't really care what it is called except really disliking introducing the term "problem ID".

Agreed.

> Fwiw "short name" _is_ a very common name in computing for this particular type of identifier. So it's not some outlandish Kattis invention.

Exactly.

> I like @thorehusfeldt's suggestion in theory, but suspect that there might be some non-negligible cost to moving from `\problemname` to `\problemtitle` unfortunately, so there might be some opposition to it?

I'm not even sure I like it in theory, but I definitely feel that there might be a cost, so I am leaning towards the status quo. I.e. *if* the suggestion is an improvement, I at least think it's not enough of an improvement to be worth a change.

> Anyway, I'm going to throw in a compromise suggestion of calling this the `problem_short_name`: it's still only used as a problem spec placeholder, so I think it's fine if it's a bit long, and with the `problem_` there's not really much room for misunderstanding.

Yeah... I definitely don't love it... it's very long... and I don't see the issue to begin with. What other name would one confuse this with? Would you read the main "name" in the main problem definition file and think "oh, this is probably the name of a validator"?

**Comment by niemela** [comment]
> Honest question: Is the problem ID that Open Kattis uses (which until recently was visible in the UI, but now is hidden away and only can be found in the problem URL) equal to the `name_of_problem_package_directory` ? (My experience tells me yes, because I’ve been asked to change the `name_of_problem_package_directory` a few times.) But there may be a further level or reference I’m not privy to (such as mapping the `open_kattis_url_base` to `name_of_problem_package_directory` .)

"Yes", but that's a Kattis implementation detail.

I say yes in quotes because we *can* override this name when installing.

> I do know that “my” problems on `itu.kattis` are referred to as `itu.blabla` even though the `name_of_problem_package_directory` if `blabla`.

Well.. there is a lot to unpack here (I can give you a call if you want all the details, I don't want to write a thesis here...)..

...but note that you can't know what the `name_of_problem_package_directory` is for *our* copy of your problem.

**Comment by thorehusfeldt** [comment]
I propose to use the terms

* the name of the package, the package name, `<package_name>`

for the string of alphanumeric characters used as the name of the top-level directory of a problem package. This is the variable called `dirname` in BAPCtools and `short_name` in `class Problem` in `verifyproblem`.

It gives the core concept (the “package”, which is what the spec is actually _about_) a name, so we can talk about it.

1. Unconfusable: Package name is different from problem name (and the many other names – validators, test groups, etc. in the package).
2. Descriptive: `hello` _is_ the name of the problem package.
3. It works well in body text. “The name of the package is …”, “… the package name must consist of…”
4. It makes no claim about how long it is, so `guess2` can be the package name of a problem whose English name is “Guess”.
5. Unlike `problem_short_name` it does not pretend to correlate with the name of the problem: `wurmprobleme` can be the package name for the problem whose English name is “Worm Worries”.
6. It doesn’t pretend to be a globally unique ID to anybody.

**Comment by thorehusfeldt** [comment]
Introduced in 3297fc515b24cd23b0868f9b9b70a770bac0fc2a
